# Generated by Django 5.0.2 on 2025-06-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_frw', '0003_itemimage_repairrequest_delete_imageupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pict',
            field=models.ImageField(blank=True, default='profile_pic/default.jpg', upload_to='profile_pics/'),
        ),
    ]
